# Generated by Django 4.2.14 on 2024-07-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('structures', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('texture', models.ImageField(upload_to='texture')),
                ('surface', models.PositiveIntegerField()),
            ],
        ),
    ]
